export const USER_DELETE_ACTION = "USER_DELETE_ACTION";
export const USER_ADD_ACTION = "USER_ADD_ACTION";
export const USER_FAVOURITE_ACTION = "USER_FAVOURITE_ACTION";
export const USERS_SORT_BY_NUMBER_ASC = "USERS_SORT_BY_NUMBER_ASC";
export const USERS_SORT_BY_NUMBER_DESC = "USERS_SORT_BY_NUMBER_DESC";
